### ISSUE TITLE
Does not work at the latest SDK.

### ISSUE THREAD

**Issue by granoeste** [fluttercommunity/flutter_wear_plugin#1]
Could you support the latest SDK version?

> Running "flutter packages get" in flutwear...
> The current Flutter SDK version is 0.4.4.
> 
> Because flutwear depends on wear any which requires Flutter SDK version >=0.3.1 <0.4.0, version solving failed.
> pub get failed (1)

**Comment by slightfoot** [comment]
This issue is now resolved in version `0.1.0` released yesterday. Closing issue.
