### ISSUE TITLE
compileOnly files('C:\\Android\\flutter\\bin\\cache\\artifacts\\engine\\android-x64\\flutter.jar') breaks build on non-windows environments

### ISSUE THREAD

**Issue by sdstolworthy** [fluttercommunity/flutter_wear_plugin#13]
https://github.com/fluttercommunity/flutter_wear_plugin/blob/87ef7bb7fd43b39bd26bd4d3f9c44f843498e46f/android/build.gradle#L49

This line breaks builds on non-Windows environments.

**Comment by alexjones1103** [comment]
Bump on getting this merge - currently using regex to fix on my pipeline ;)

**Comment by johnson-yeap** [comment]
When would this fix be released? @mjohnsullivan

**Comment by MarceloRab** [comment]
up

**Comment by slightfoot** [comment]
@johnson-yeap just releasing it now. Sorry chaps. Left that line in by mistake.

**Comment by slightfoot** [comment]
Thanks @sdstolworthy and everyone. Published fix as 1.1.0 https://pub.dev/packages/wear/versions/1.1.0
