### ISSUE TITLE
Ambient Mode not working in release mode

### ISSUE THREAD

**Issue by gongbj0113** [fluttercommunity/flutter_wear_plugin#16]
AmbientMode worked fine in debug mode,
but when I build apk in release mode, it doesn't work.

The flutter should have rebuilt the screen right before it entered ambient mode, but it seemed that rebuild didn't occur.
The screen just stopped when it entered ambient mode. (I'm using Samsung Galaxy Watch 5)

![image](https://user-images.githubusercontent.com/34854639/189401397-7fbd8034-47ba-4434-a954-708f3e27f525.png)

I tried to get the event log, but nothing was printed. (Other prints were received correctly.)

**Comment by zbejas** [comment]
Same issue. Works 'fine' in debug (also works in profile, just checked), but nothing is happening in release.

```dart
AmbientMode(builder: (context, mode, child) {
        return mode == WearMode.ambient
            ? AmbientScreen(
                manager: manager,
              )
            : ActiveScreen(
                manager: manager,
                box: box,
              );
      }),
```

Edit: also using Galaxy Watch 5.

**Comment by Rexios80** [comment]
Until that PR gets merged, just add the following to your app's proguard config

```
-keep class com.mjohnsullivan.flutterwear.wear.** { *; }
```

**Comment by Rexios80** [comment]
I released the [wear_plus](https://pub.dev/packages/wear_plus) plugin which contains the necessary fixes

**Comment by gongbj0113** [comment]
Thank you for your work. I appreciate it.
