### ISSUE TITLE
Unable to release the app APK on Google Play

### ISSUE THREAD

**Issue by johnson-yeap** [fluttercommunity/flutter_wear_plugin#2]
Able to run the debug app on Motorola Moto 360. 

However, Google Play is showing the following message when deployed.

![image](https://user-images.githubusercontent.com/6791060/50725034-5c888a80-1132-11e9-925d-420bc8c4f716.png)

**Comment by SurajLad** [comment]
i know i am late but are you sure that you have added Flag in manifest for wearOS App ?.

```<uses-feature android:name="android.hardware.type.watch" />```

**Comment by slightfoot** [comment]
This issue is now resolved in version `0.1.0` released yesterday. Closing issue.
