### ISSUE TITLE
Reply already submitted - Fatal exception

### ISSUE THREAD

**Issue by JFtechOfficial** [fluttercommunity/flutter_wear_plugin#4]
Getting exemption after doing a swipe from left to right (on an emulator). Switching context with in-app software button works, switching context with the emulator back button works, switching context with gesture doesn't. Any ideas?
Many thanks in advance!

D/AndroidRuntime( 3419): Shutting down VM
E/AndroidRuntime( 3419): FATAL EXCEPTION: main
E/AndroidRuntime( 3419): Process: com.mjohnsullivan.flutterwear.wearexample, PID: 3419
E/AndroidRuntime( 3419): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 3419): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl$1.reply(FlutterNativeView.java:197)
E/AndroidRuntime( 3419): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime( 3419): 	at com.mjohnsullivan.flutterwear.wear.WearPlugin$handleShapeMethodCall$1.onApplyWindowInsets(WearPlugin.kt:61)
E/AndroidRuntime( 3419): 	at android.support.v4.view.ViewCompat$ViewCompatApi21Impl$1.onApplyWindowInsets(ViewCompat.java:1307)
E/AndroidRuntime( 3419): 	at android.view.View.dispatchApplyWindowInsets(View.java:9799)
E/AndroidRuntime( 3419): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
E/AndroidRuntime( 3419): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
E/AndroidRuntime( 3419): 	at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:1667)
E/AndroidRuntime( 3419): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2080)
E/AndroidRuntime( 3419): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1466)
E/AndroidRuntime( 3419): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
E/AndroidRuntime( 3419): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime( 3419): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime( 3419): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
E/AndroidRuntime( 3419): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime( 3419): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 3419): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3419): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 3419): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 3419): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3419): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 3419): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 3419): Sending signal. PID: 3419 SIG: 9
Application finished.

**Comment by slightfoot** [comment]
This issue is now resolved in version `0.1.0` released yesterday. Closing issue.
