### ISSUE TITLE
add null safety support

### ISSUE THREAD

**Issue by avkonst** [fluttercommunity/flutter_wear_plugin#8]
Hi,
You have got nice little toolkit. Would it be possible to upgrade it to null safety?

**Comment by Rexios80** [comment]
Done in #11

**Comment by dotupNET** [comment]
There's no response from owner. I created a fork.

[https://pub.dev/packages/dotup_flutter_wear](https://pub.dev/packages/dotup_flutter_wear)

[https://github.com/dotupNET/dotup_flutter_wear](https://github.com/dotupNET/dotup_flutter_wear)

**Comment by slightfoot** [comment]
@dotupNET just FYI this was pushed and fixed. If you have other changes in your package and want to bring them back into the upstream just @ mention me and I'll get a notice.
